<?php
/**
 * @var \Bluz\View\View $this
 */
?>
    <script>
        // use data-spy="grid" for use AJAX for reload grid
        require(['bluz.categories', 'bluz.grid']);
    </script>
<?php $uid = uniqid('form_'); ?>
    <form id="<?= $uid ?>" action="<?= $this->url('menu', 'crud') ?>"
          class="form-horizontal ajax" method="<?= $method ?>">
        <input type="hidden" name="id" value="<?= $row->id ?>"/>
        <input type="hidden" name="_method" value="<?= $method ?>"/>

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?= __('Edit page') ?></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="control-label col-lg-2"
                           for="title"><?= __('Title') ?>:</label>

                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="title"
                               name="title" value="<?= esc($row->title) ?>"
                               required/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-2"
                           for="description"><?= __('Description') ?>:</label>

                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="description"
                               name="description"
                               value="<?= esc($row->description) ?>"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-2"
                           for="categoryId"><?= __('Category') ?>:</label>

                    <div class="col-lg-6">
                        <select class="form-control root-category-list"
                                name="categoryId" id="dish-category">
                            <?php foreach ($foodCategories as $category) : ?>
                                <option
                                    value="<?php echo esc($category['id']) ?>"
                                    <?php if (esc($category['id']) == esc($row->categoryId)) : ?>
                                        <?php echo "selected=selected"; ?>
                                    <?php endif ?>
                                ><?php echo esc($category['name']) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-2"
                           for="cost"><?= __('Cost') ?>:</label>

                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="cost"
                               name="cost" value="<?= esc($row->cost) ?>"
                               required/>
                    </div>
                </div>

                <h4>Used media</h4>

                <div class="form-group row clearfix ">
                    <?php if (isset($row)): ?>
                        <?php foreach ($row->getRelations('Media') as $img): ?>
                            <div class="panel panel-default col-lg-3">
                                <div class="panel-heading">
                                    <div class="pull-right">
                                        <a href="<?= $this->url('menu',
                                            'delete-media',
                                            [
//                                                'mediaId' => $img['id'],
//                                                'dishId' => $row['id']
                                            ]) ?>"
                                           class="confirm btn btn-xs btn-danger ajax"
                                        >
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <a href="<?= $this->baseUrl($img['file']) ?>"
                                       class="thumbnail bluz-preview">
                                        <img style="height:80px"
                                             src="<?= $this->baseUrl($img['preview'] ?: $img['file']) ?>"
                                             class="img-polaroid"
                                             alt="<?= $img['title'] ?>"/>
                                    </a>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>


                </div>


                <h4>Unused media</h4>

                <div class="form-group row clearfix ">
                    <?php if (isset($unusedMedia)): ?>
                        <?php foreach ($unusedMedia as $img): ?>
                            <div class="panel panel-default col-lg-3">
                                <div class="panel-heading">
                                    <div class="pull-right">
                                        <a href="<?= $this->url('menu',
                                            'add-media', [
                                                'mediaId' => $img['id'],
                                                'dishId' => $row['id']
                                            ]) ?>"
                                           class="btn btn-xs btn-primary ">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <a href="<?= $this->baseUrl($img['file']) ?>"
                                       class="thumbnail bluz-preview">
                                        <img style="height:80px"
                                             src="<?= $this->baseUrl($img['preview'] ?: $img['file']) ?>"
                                             class="img-polaroid"
                                             alt="<?= $row['title'] ?>"/>
                                    </a>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>


                </div>

                <div class="modal-footer">
                    <button type="submit"
                            class="btn btn-primary"><?= __('Save') ?></button>
                    <a href="#" class="btn btn-default"
                       data-dismiss="modal"><?= __('Close') ?></a>
                </div>
            </div>
    </form>

<?php
// need for plain request
if (isset($errors)) :
    $data = json_encode(['errors' => $errors]);
    $this->headScript('require(["bluz.form"], function(form) {
        form.notices($("#' . $uid . '"), ' . $data . ');
    });');
endif;
?>