<?php
/**
 * @var \Bluz\View\View $this
 */
?>
    <script>
        require(['bluz.categories', 'menu.fileupload']);
    </script>
<?php $uid = uniqid('form_'); ?>
    <form id="<?= $uid ?>" action="<?= $this->url('menu', 'crud') ?>"
          class="form-horizontal ajax" method="<?= $method ?>">
        <input type="hidden" name="id" value="<?= $row->id ?>"/>
        <input type="hidden" name="_method" value="<?= $method ?>"/>

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?= __('Edit page') ?></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="control-label col-lg-2"
                           for="title"><?= __('Title') ?>:</label>

                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="title"
                               name="title" value="<?= esc($row->title) ?>"
                               required/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-2"
                           for="description"><?= __('Description') ?>:</label>

                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="description"
                               name="description"
                               value="<?= esc($row->description) ?>"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-2"
                           for="categoryId"><?= __('Category') ?>:</label>

                    <div class="col-lg-6">
                        <select class="form-control root-category-list"
                                name="categoryId" id="dish-category">
                            <?php foreach ($foodCategories as $category) : ?>
                                <option
                                    value="<?php echo esc($category['id']) ?>"
                                    <?php if (esc($category['id']) == esc($row->categoryId)) : ?>
                                        <?php echo "selected=selected"; ?>
                                    <?php endif ?>
                                ><?php echo esc($category['name']) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-2"
                           for="cost"><?= __('Cost') ?>:</label>

                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="cost"
                               name="cost" value="<?= esc($row->cost) ?>"
                               required/>
                    </div>
                </div>

                <span class="btn btn-success fileinput-button">
                     <i class="glyphicon glyphicon-plus"></i>
                    <span>Select files...</span>
                    <!-- The file input field used as target for the file upload widget -->
                    <input id="fileupload" type="file" name="files[]" multiple>
                </span>


                <br>
                <!-- The container for the uploaded files -->
                <div id="files" class="files">
                </div>


            </div>
            <div class="modal-footer">
                <button type="submit"
                        class="btn btn-primary"><?= __('Save') ?></button>
                <a href="#" class="btn btn-default"
                   data-dismiss="modal"><?= __('Close') ?></a>
            </div>
        </div>
    </form>


<?php
// need for plain request
if (isset($errors)) :
    $data = json_encode(['errors' => $errors]);
    $this->headScript('require(["bluz.form"], function(form) {
        form.notices($("#' . $uid . '"), ' . $data . ');
    });');
endif;
?>