<?php
/**
 * @var \Application\Menu\Row $dish
 */
?>
<form action="<?= $this->url('menu', 'media', ['dishId' => $dish->id]) ?>"
      class="form-horizontal ajax" method="post"
      enctype="application/x-www-form-urlencoded">
    <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal">&times;</button>
        <h3 class="modal-title"><?=__('Choose media for %s', $dish->title)?></h3>
    </div>
    <div class="modal-body">
        <div class="col-lg-12 form-group input-group">
            <?php if (!empty($dishMedia) && is_array($dishMedia)): ?>
                <?php foreach ($dishMedia as $i => $media): ?>
                    <div class="panel panel-default col-lg-3">
                        <div class="panel-heading">
                            <div class="pull-right">
                                <input type="checkbox" name="media[]"
                                       value="<?= $media->id ?>" <?= ('checked') ?>/>
                            </div>
                        </div>
                        <div class="panel-body">
                            <a href="<?= $this->baseUrl($media['file']) ?>"
                               class="thumbnail bluz-preview">
                                <img style="height:80px"
                                     src="<?= $this->baseUrl($media['preview'] ?: $media['file']) ?>"
                                     class="img-polaroid"
                                     alt="<?= $media['title'] ?>"/>
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if (!empty($unusedMedia)): ?>
                <?php foreach ($unusedMedia as $i => $media): ?>
                    <div class="panel panel-default col-lg-3">
                        <div class="panel-heading">
                            <div class="pull-right">
                                <input type="checkbox" name="media[]"
                                       value="<?= $media['id'] ?>"/>
                            </div>
                        </div>
                        <div class="panel-body">
                            <a href="<?= $this->baseUrl($media['file']) ?>"
                               class="thumbnail bluz-preview">
                                <img style="height:80px"
                                     src="<?= $this->baseUrl($media['preview'] ?: $media['file']) ?>"
                                     class="img-polaroid"
                                     alt="<?= $media['title'] ?>"/>
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>


        </div>

    </div>
    <div class="modal-footer">
        <button type="submit"
                class="btn btn-primary"><?= __('Save changes') ?></button>
        <a href="#" class="btn btn-default"
           data-dismiss="modal"><?= __('Close') ?></a>
    </div>
</form>
